config/routes.rb
Limapp::Application.routes.draw do
  
  resources :users do
    resources :soundtracks
  end
  
end

app/models/soundtrack.rb
class Soundtrack < ActiveRecord::Base
  belongs_to :user
  has_many :tracks

  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :tracks  
end

app/models/track.rb
class Track < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessible :first_name, :last_name, :username, :dob
  has_one :soundtrack
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/soundtracks_controller.rb
class SoundtracksController < ApplicationController
  
  def new
    @user = User.find(params[:user_id])
    @soundtrack = Soundtrack.new
    @soundtrack.build_user
   end

   def create
     @soundtrack = Soundtrack.new(params[:soundtrack])

     if @soundtrack.save
       render(:action => :show)
     else
       render(:action => :new)
     end
   end

   def show
   end

   def edit
   end

   def update
     if @soundtrack.update_attributes(params[:soundtrack])
       render(:action => :show)
     else
       render(:action => :edit)
     end
   end   
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :find_user,  :only => [ :show, :edit, :update, :destroy ]

  def index
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    
    if @user.save
      render(:action => :show)
    else
      render(:action => :new)
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(params[:user])
      render(:action => :show)
    else
      render(:action => :edit)
    end
  end
  
  protected
    def find_user
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to users_path
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/soundtracks_helper.rb
module SoundtracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Limapp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/soundtracks/_form.erb
Soundtrack Form

app/views/soundtracks/index.html.erb
Soundtracks Index View

app/views/soundtracks/new.html.erb
<%= form_for(@user, @soundtrack) do |form| %>
  <%= render(:partial => 'form', :locals => { :form => form }) %>
<% end %>

app/views/soundtracks/show.html.erb
Soundtrack Show View

app/views/users/_form.erb
<%= form.label :username %>:
<%= form.text_field :username %><br />

<%= form.label :first_name %>:
<%= form.text_field :first_name %><br />

<%= form.label :last_name %>:
<%= form.text_field :last_name %><br />

<%= form.label :dob %>:
<%= form.date_select(:dob, :start_year => 1900, :end_year => 2013) %><br />

<%= form.submit %>

app/views/users/edit.html.erb
<%= form_for @user do |form| %>
  <%= render(:partial => 'form', :locals => { :form => form }) %>
<% end %>
<br/>
<%= link_to("cancel", user_path(@user)) %>

app/views/users/index.html.erb
Users Index View

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <%= render(:partial => 'form', :locals => { :form => form }) %>
<% end %>

app/views/users/show.html.erb
<%= @user.first_name %><br/>
<%= @user.last_name %><br/>
<%= @user.username %><br/>
<%= @user.dob %><br/>
<br/>

<%= link_to("edit", edit_user_path(@user)) %>